Support to Android 12
This should fix the problem:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.jackbayliss.nfcreader.NfcCardReaderActivity}: java.lang.IllegalArgumentException: com.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.